apiVersion: v1
data:
  password: IV8tUTQ1czcrdypFOGtUYg==
  username: Q049c3ZjYWNjdC1hdW9wZW5zaGlmdCxPVT1TdGFtcGVkUHJvY2Vzc0lEcyxPVT1Mb2dpY2FsIFNlY3VyaXR5LE9VPUNvcmUgRGlyZWN0b3J5IFNlcnZpY2VzLERDPUZORklTLERDPWNvbQ==
kind: Secret
metadata:
  name: ad-bind-credentials
  namespace: group-sync-operator
type: Opaque

